#' Boys and Girls attitudes to school simulated data set
#' 
#' A simulated data set of 500 student responses without missing values. This represents 250 boys and 250 girls assigned equally to a control and an intervention group. By design, the mean attitude response across the 7 item scale for the boys in the control group should be 3.4 while for the girls this should be 2.9. The effect size for the boys is set so that the mean response of the boys in the intervention group is 3.9 while the mean response for the girls in the intervention group is 3.7.  Thus there should be observable differences for both genders by virtue of being in the intervention group and the effect should be stronger for girls than boys. The data should simulate a "closing the gap" type intervention.
#' 
#' @format ## `boys_girls_attitudes`
#' A data frame with 500 participants (rows) and 11 variables (columns):
#' \describe{
#'   \item{id}{FACTOR: Participant Identifier of the form G_GRP# where G is B (boy) or G (girl), GRP is CON (control) or INT (intervention) and # is a number from 1 to 125}
#'   \item{Treatment}{FACTOR: Either Control or Intervention}
#'   \item{Gender}{FACTOR: Either boy or girl}
#'   \item{x1, x2, x3, x4, x5, x6, x7}{FACTOR: responses on scale of 1 to 5 corresponding to students actual responses}
#'   \item{Mean}{NUMERIC: mean of response scores}
#'}
#'@source Generated by /data-raw/boys_girls_attitudes.R
#'
"boys_girls_attitudes"