#' make_longer()
#' 
#' Make a dataframe generated by `generateData()` into long form following tidy rules 
#'
#' @param .data A wide dataframe generated by generateData()
#'
#' @return A long dataframe
#' @export
#'
#' @examples
#' generateData(n = 5, 
#'              scalewidth = 3, 
#'              return = "raw")
#'
#'generateData(n = 5, 
#'             scalewidth = 3, 
#'             return = "raw")%>%
#'  make_longer()

make_longer <- function(.data){
  .data%>%
    tidyr::pivot_longer(
      cols = dplyr::where(is.numeric), 
      names_to = "Case", 
      values_to = "Response")%>%
    mutate(Treatment = as.factor(paste(Treatment,Case,sep = "_")))%>%
    select(-Case)
}