#' to_numeric
#' 
#' Converts Likert data generated by `generateData()` from factor form to its underlying numeric format.  By default works on any columns that match the RegEx in `match`.
#' #'
#' @param .data A data frame generated by `generateData()`
#' @param match A RegEx to match. By default `^(x|e)[1-9+$]`
#'
#' @return A matching data frame
#' @export
#'
#' @examples
#' generateData(return = "raw")%>%
#'   to_numeric()
#'   
#' generateData(return = "raw")%>%
#'   label_variables()%>%
#'   to_numeric()
#' 
to_numeric <- function(.data, match = "^(x|e)[1-9]+$|^Response$"){
  .data %>%
    dplyr::mutate(
      dplyr::across(
        tidyselect::matches(match),
        function(x){
          if(is.factor(x)){
            as.numeric(x)
          }
        }
    ))
}