#' Visualise Likert Data
#' 
#' A quick wrapper to visualize data generated by `GenerateData()` in a way that allows adjustments to be made easily. If data are numeric then density plots are returned, if data are factors then bar plot is returned.
#'
#' @param .data A data frame generated by `generateData()`. Can be in wide or long format
#' @param vars An optional character vector or list of variables to include in the display
#'
#' @return A ggplot2 object
#' @export
#'
#' @examples
#' 
#' # Generate 1000 cases and show the average response
#' generateData(n=1000)%>%
#'   visualise()
#' 
#' # Generate 100 cases for an intervention of effect size 1 and only show data from x1 and x2 
#' generateData(n=100, return = "raw", effect = 1)%>%
#'   visualise(vars = c("x1","x2"))
#'   
#' # Generate 500 cases for an intervention of effect size -1 and only show data from x1 and 
#' # applying Temporal Lables 
#' generateData(n=100, return = "raw", effect = 1)%>%
#'   label_variables(scale = "TE")%>%
#'   visualise(vars = c("x1"))
visualise <- function(.data, vars = NULL){
  
  if("Response" %in% names(.data)){
    .data <- .data %>%
      tidyr::drop_na()
  }else{
    .data <- .data %>%
      LikertGenerator::make_longer()%>%
      tidyr::drop_na()
  }
  
  if(!is.null(vars)){
    .data <- .data %>%
      dplyr::filter(Item %in% vars)
  }  
  
  plt <- .data %>%
    ggplot2::ggplot(ggplot2::aes(x = Response, fill = Item))
  
  if(is.factor(.data$Response)){
    plt <- plt +
      ggplot2::geom_bar(position="identity", alpha = 0.3, colour = "black")+
      ggplot2::scale_x_discrete(labels = scales::label_wrap(10))
  }else{
    plt <- plt +
      ggplot2::geom_density(ggplot2::aes(colour = Item),alpha = 0.3)
  }
  plt <- plt +
    ggplot2::facet_wrap(vars(Treatment))
  return(plt)
}


#' @rdname visualise
#' @export
visualize <- visualise